blank_issues_enabled: false
contact_links:
  - name: آسیب‌پذیری امنیتی
    url: https://github.com/shahinesi/chatgpt-persian-rtl/security/advisories/new
    about: مشکلات امنیتی را به‌صورت خصوصی گزارش کنید.
